- name: Install Tetration Sensor MSI
  win_package:
      path: C:\Temp\update\TetrationAgentInstaller.msi
      state: absent

- name: Remove Tetration Sensor Directory
  win_file:
    state: absent
    path: 'C:\Program Files\Cisco Tetration'